name: Scalafmt

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    runs-on: ubuntu-22.04
    if: github.repository == 'apache/pekko-http'
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check project is formatted
        uses: jrouly/scalafmt-native-action@v4
        with:
          arguments: '--list --mode diff-ref=origin/main'
