name: Publish 1.0 docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish documentation to nightlies.apache.org
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-http'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: 1.0.x

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Build Documentation
        run: |-
          sbt -Dpekko.genjavadoc.enabled=true "set ThisBuild / version := \"1.0.0\"; docs/paradox; unidoc"
        env:
          JAVA_OPTS: "-verbose:gc -Xmx4g"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-http/1.0.0/
          mkdir -p target/nightly-docs/docs/pekko-http/1.0/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-http/1.0.0/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-http/1.0/docs
          rm -r docs/target/paradox/site/main/
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-http/1.0.0/api
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-http/1.0/api
          rm -r target/scala-2.13/unidoc
          cp -r target/javaunidoc target/nightly-docs/docs/pekko-http/1.0.0/japi
          cp -r target/javaunidoc target/nightly-docs/docs/pekko-http/1.0/japi
          rm -r target/javaunidoc

      - name: Upload 1.0.x nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-http/1.0.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.0 nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-http/1.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}          
